---
title: "FinalMarkdown"
author: "Giovani Gutierrez"
date: "2024-06-06"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
library(tidyverse)
library(igraph)
library(ggplot2)
library(patchwork)
library(Matrix)
```

# 1

```{r}
edgelist <- read_csv('large_twitch_edges.csv', show_col_types = FALSE)

features <- read_csv(
  'large_twitch_features.csv',
  col_types = list(language = col_factor(), mature = col_logical(),
                   dead_account = col_logical(), affiliate = col_logical())
) %>% relocate(numeric_id, .before = views) # move id to first col
```

```{r}
edgelist <- matrix(unlist(edgelist), ncol = 2) + 1
features$numeric_id <- features$numeric_id + 1 

g <- graph_from_edgelist(edgelist, directed = FALSE) %>% 
  set_vertex_attr(name = 'views', value = features$views) %>% 
  set_vertex_attr(name = 'mature', value = features$mature) %>% 
  set_vertex_attr(name = 'life_time', value = features$life_time) %>% 
  set_vertex_attr(name = 'dead_account', value = features$dead_account) %>% 
  set_vertex_attr(name = 'language', value = features$language) %>% 
  set_vertex_attr(name = 'affiliate', value = features$affiliate)
```

```{r}
summary(features)
```

```{r}
vert_de <- V(g)[language == 'DE'] # german speaking nodes
g_de <- induced_subgraph(g, vids = vert_de)
comp <- components(g_de)
biggest_cluster_id <- which.max(comp$csize)
vert_ids <- V(g_de)[comp$membership == biggest_cluster_id]
g1 <- induced_subgraph(g_de, vert_ids)
summary(g1)
```

```{r}
set.seed(123)
par(mar = c(0, 0, 0, 0))

plot(g1, vertex.size = 2, vertex.label = NA, layout = layout_with_fr, vertex.color='#88398A', edge.color = 'gray80', vertex.frame.width=0.1)
```

```{r}
deg <- degree(g1)

hist(deg, breaks = seq(-1,(max(deg)+1), by = 0.5), 
     main = 'Histogram of Node Degree',
     xlab = 'Degree', 
     )
```

```{r}
is_simple(g1)

is_connected(g1)

edge_density(g1)

transitivity(g1)

mean_distance(g1, weights = NA, directed = FALSE, unconnected = FALSE)

diameter(g1, directed = FALSE, unconnected = FALSE)
```



```{r}
vert_fr <- V(g)[language == 'FR'] # french speaking nodes
g_fr <- induced_subgraph(g, vids = vert_fr)
comp <- components(g_fr)
biggest_cluster_id <- which.max(comp$csize)
vert_ids <- V(g_fr)[comp$membership == biggest_cluster_id]
g2 <- induced_subgraph(g_fr, vert_ids)
summary(g2)
```

```{r}
set.seed(123)
par(mar = c(0, 0, 0, 0))

plot(g2, vertex.size = 2, vertex.label = NA, layout = layout_with_lgl, vertex.color='tomato', edge.color = 'gray80', vertex.frame.width=0.1)
```

```{r}
adj_mat <- as_adjacency_matrix(g1,sparse = TRUE)
image(Matrix(adj_mat))
```
```{r}
sg1 <- induced_subgraph(g, sample(V(g), 500))
sg2 <- induced_subgraph(g, sample(V(g), 1000))
```

```{r}
par(mar=c(0,0,0,0))
plot(sg1, vertex.label = NA, layout = layout_with_kk, vertex.size = 5, vertex.color = 'tomato')
```

```{r}
par(mar=c(0,0,0,0))
plot(sg2, vertex.label = NA, layout = layout_on_sphere, vertex.size = 5, vertex.color = 'tomato')
```

